### ISSUE TITLE
Add support for bugfix command

### ISSUE THREAD

**Issue by nchelluri** [petervanderdoes/gitflow#156]
Hi,

We are using JIRA and Stash (Atlassian products) in our development, along with git-flow-avh.

JIRA/Stash, as we have configured them, are pretty much following standard Git flow practice. However, they have an option to create a branch with the "bugfix" prefix. It operates like "feature" (branches from develop).

I am wondering if we can get a copy of the "feature" command that is called "bugfix".

Thank you.

**Comment by kvervo** [comment]
+1

**Comment by dakotahawkins** [comment]
This would be awesome.

**Comment by deep-orca** [comment]
+1

**Comment by petervanderdoes** [comment]
Took a while but it's implemented per commit aefdf5412673c85f23f9f4542e3f6c3a4b42b82f version 1.9.0-dev.48

**Comment by McDoit** [comment]
I have a suggestion for a extension to this functionality
When you finish a bugfix  and have a active release, I think it would be a good idea if the bugfix would also get merged into the release.
As you cant start a hotfix for it, nor restart the release with only that fix in a simple way.

Any comments on that?

**Comment by petervanderdoes** [comment]
I guess it would make sense in certain situations. A small problem would be if you had multiple release branches.
If it was to be implemented it would be with a parameter, something like:

    git flow bugfix finish --release <name>

Of course you can always start a feature or bugfix branch from the release branch as well.
