### ISSUE TITLE
Feature proposal - cherry pick commits from hotfix to develop

### ISSUE THREAD

**Issue by simonweil** [petervanderdoes/gitflow#164]
The goal of this proposal is to keep a clean history without too many splits in the `git log` graph history.

Add a `--cherry-pick` option to hotfix finish command: `git flow hotfix finish --cherry-pick` that will cherry pick the relevant commits from the hotfix branch to the develop branch instead of the merge.

The hashes for the cherry-pick can be found with this command:
```
git log --oneline develop..hotfix/[name]  | \ 
grep -vE "^[a-z0-9]* Merge branch '[^'].*?'$" | \ 
cut -f1 -d" "
```

**If this is a relevant feature, I'll issue a pull request.**

**Comment by petervanderdoes** [comment]
I'm assuming you mean master branch instead of develop in the script as the hotfix branch is branched from the master.

On a side note to get the hashes it's better to use:
`git rev-list master..hotfix/[name]`

**Comment by simonweil** [comment]
You are right, I meant 'master' and thank you about `rev-list`.

Should I submit a PR?

**Comment by petervanderdoes** [comment]
Sure, I think it's a nice option to have.
Thanks

**Comment by simonweil** [comment]
Seems that I've already sent the PR quite a while ago #165 .
Please comment on the PR and I'll fix what you see necessary.

**Comment by petervanderdoes** [comment]
Continue discussion on #165
