### ISSUE TITLE
feature finish default behavior

### ISSUE THREAD

**Issue by nbartels** [petervanderdoes/gitflow#181]
Hi there,

I think the default behavior for the ```git flow feature finish``` is not the best. It would be better to keep the remote branch and delete it only if the user changed the config.

BTW config: is this command the correct one to change the "keep remote" system wide?

```git config --global --bool feature.finish.keepremote true```

**Comment by petervanderdoes** [comment]
As the local branch is deleted by default as well, I figured the remote should have the same behavior.
Almost on the config it's

`git config --global gitflow.feature.finish.keepremote true`
