### ISSUE TITLE
Publish unexpectedly fails to set rebase = true in the presence of branch.autosetuprebase always

### ISSUE THREAD

**Issue by oddnoc** [petervanderdoes/gitflow#183]
The way the flow scripts implement cmd_publish (push followed by explicit config edits) prevents the operation of autosetuprebase that you get when you do a `git push -u origin some_branch`, which defeats the purpose of having autosetuprebase turned on.

I would be happy to submit patches, but, not knowing the rationale for the present implementation, I'm reluctant to simply jump in.

**Comment by petervanderdoes** [comment]
The publish command was inherited from the original source, I don't think much thought was given to the command at the time of implementation. 

Feel free to submit a patch, I recommend doing one flow command first before patching all the rest.
Makes it easier to review and when we agree on implementation it just needs to be integrated in the rest of the flow commands.
