### ISSUE TITLE
Proper usage question or bug on combining parameters with release finish

### ISSUE THREAD

**Issue by dpwspoon** [petervanderdoes/gitflow#185]
git flow release finish -m -p 1.0 doesn't seem to do the -p though does not return any errors

Apologies if I'm doing something wrong but I've tried several variations of using the -m and -p together and I've only gotten the -m to work.  Though if I try with 

```
git flow release finish -p 1.0
```

the -p seems to take affect

**Comment by petervanderdoes** [comment]
When using `-m`, it needs to be followed by the message. If you check you log, your commit message on probably is `-p`

**Comment by dpwspoon** [comment]
K I tried
```
git flow release finish -m "released 2.4" -p 2.4
```
and got 
```
flags:FATAL the available getopt does not support spaces in options
```

**Comment by petervanderdoes** [comment]
Which OS and which version of getopt are you using?

**Comment by dpwspoon** [comment]
I've updated gitflow to 1.8.0 and the issue has seem to gone away. Thanks.
