### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jpetereit** [petervanderdoes/gitflow#189]
The wiki does not mention the Ubuntu package `git-flow` which seems to be this AVH edition since Trusty: http://packages.ubuntu.com/search?keywords=git-flow

Is this deliberately left out? Is there a reason for not using `apt-get install git-flow`? If not, it might be nice to add this to the wiki's installation instructions. If yes, a note why not to use the package might be interesting as well.

**Comment by petervanderdoes** [comment]
I never knew my version was packaged in Ubuntu until a few months ago. There is no reason not to use the Ubuntu version, besides that sometimes Ubuntu lacks updates, but I'll add it to the wiki.
