### ISSUE TITLE
Fast-forward merges are used, which lose history

### ISSUE THREAD

**Issue by greenrd** [petervanderdoes/gitflow#205]
When I finish a feature, a fast-forward merge into the develop branch is done if possible. This means that it is no longer possible to know which feature branch introduced a commit, unless that information is manually duplicated in the commits.

The original git-flow repo does not have this behaviour.

**Comment by vmrob** [comment]
While it might not be the original behavior, there are many options you can set on a per-repository basis. Maybe there's even a global config?

Take a look at some of them here:

https://github.com/petervanderdoes/gitflow/wiki/Reference:-Configuration

For your case, you're probably going to want the following:

    git config gitflow.feature.finish.no-ff TRUE

**Comment by petervanderdoes** [comment]
You can do a global setting as well. As per the above example to set it global:

    git config --global gitflow.feature.finish.no-ff TRUE
