### ISSUE TITLE
Modify GitHub installation instructions for Windows to include correct repository.

### ISSUE THREAD

**Issue by vmrob** [petervanderdoes/gitflow#207]
Currently, the wiki [installation instructions](https://github.com/petervanderdoes/gitflow/wiki/Installing-on-Windows) call for

    C:\GitHub> git clone --recursive git://github.com/nvie/gitflow.git

when I think it should be

    C:\GitHub> git clone --recursive git://github.com/petervanderdoes/gitflow.git

**Comment by petervanderdoes** [comment]
Thanks, fixed now
