### ISSUE TITLE
Release doesn't get merged back to master

### ISSUE THREAD

**Issue by Razrael** [petervanderdoes/gitflow#212]
Hello

I need to make releases based on an older commit, so I used something like "git flow release start 1.x tmpReleaseBranch"

If used with this base branch, it will not get merged back to master when using "git flow release finish 1.x", so this has to be done manually.
Since it get merged back if no base is used, I expect this behaviour to be the same when using a base.

**Comment by petervanderdoes** [comment]
The reason for not merging back into master is because I can't determine where the base originates from.
If you maintain multiple versions of your software a release could be made from a support branch and should not be merged into the master branch as that would be a totally different version.
